.\" Manpage for dep
.\" Report errors or typos to https://github.com/frc1418/dep
.TH dep 7 "22 Aug 2017" "1.0.0" "dep man page"

.SH NAME
dep \- A helpful CLI tool for deploying code to FRC robots.

.SH SYNOPSIS
.B dep
[-rw]

.SH DESCRIPTION
A helpful CLI tool for deploying code to FRC robots. Designed to take time out of the robot code deploy process by removing steps such as network connection.

.SH OPTIONS
.BR \-r
Reconnect to previous network following deploy.

.BR \-w
Force deploy over WiFi even when bridging over Ethernet.

.BR \-s
Skip tests during deploy.

.SH BUGS
Please see current issues on
.UR https\://\:github.com/frc1418/dep/issues
issue tracker
.UE ,
and report any bugs or request features you'd like.

.SH AUTHORS
This software is maintained by
.MT robotics1418@\:gmail.com
FIRST Robotics Competition Team 1418
.ME
since 2016 on
.UR https\://\:github.com/frc1418/dep
GitHub
.UE .
This manual page was written by
.MT me@\:erikboesen.com
Erik Boesen
.ME .
